### ISSUE TITLE
Missing dependency for 'request'...

### ISSUE THREAD

**Issue by bandzaw** [retroflex/MMM-AllsvenskanStandings#3]
MagicMirror fails to start with MMM-AllsvenskanStandings:
[ERROR] (node:412735) UnhandledPromiseRejectionWarning: Error: Cannot find module 'request'
Require stack:
- MagicMirror/modules/MMM-AllsvenskanStandings/node_helper.js 

Yes, I can work around this myself by installing 'request' but I believe modules with external dependencies should declare that in their package.json file.

Thank you for bringing Allsvenskan to MagicMirror!

**Comment by retroflex** [comment]
I haven't used this module in a long while myself and don't have the time to look at it right now. But feel free to make a PR and I'll look at it.

**Comment by KristjanESPERANTO** [comment]
Since `request` is deprecated and we have now `fetch` as an node internal alternative, I've removed request in my PR #4. With that change there are no external dependencies anymore :rocket: :smiley:
